server:
  port: 9090
spring:
  application:
    name: order-service
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5438/order
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

keycloak:
  realm: java
  auth-server-url: http://localhost:8080/auth
  resource: java-client
  public-client: true
  bearer-only: true